---
title: "report"
author: "María Cristina Sánchez Iglesias"
date: "16/3/2021"
output: pdf_document
params:
  selDepth
  selCore
---
```{r include=FALSE}
library(tidyverse)
core_depth_selected <- df_long %>% 
  mutate_at(c("depth", "core"), as.factor) %>%
  filter(depth == params$selDepth & core == params$selCore)
```


```{r echo=FALSE}
ggplot(core_depth_selected(),
                             aes(x=material, y=proportion))  +  theme(legend.position = "none",
                          panel.background = element_rect(fill = "white", color = "gray60")) +
                          geom_bar(stat='identity', colour="gray60", aes(fill=material)) + 
                          scale_fill_manual(values=setNames(c("palevioletred", "lightsalmon3", "orange", "lightsteelblue4", "mediumturquoise", "khaki4", 
                                                                "gold", "mediumorchid1"),
                                                              c("Quartz", "Feldspar", "Dark Lithics", "Manganese", "Forams", 
                                                                "Sponge Spicules", "Carbonate Fragments", "Pteropods"))) +
                          xlim("Quartz", "Feldspar", "Dark Lithics", "Manganese", "Forams", 
                               "Sponge Spicules", "Carbonate Fragments", "Pteropods") + 
                          ylim("R", "R-P", "P", "P-C", "C", "C-A", "A")
```