---
title: "Composition of a core at a certain depth"
author: "María Cristina Sánchez Iglesias"
output: pdf_document
params:
  selDepth: 6
  selCore: 10GGC
---
```{r include=FALSE, warning=FALSE}
library(shiny)
library(tidyverse)
library(magrittr)
library(httr)
library(readxl)
library(stringr)
library(plyr)
library(shinythemes)
library(shinyjs)
library(shinyWidgets)

GET("https://query.data.world/s/xzozlqhuagxyazzgc3avtgcaw2yqxk", write_disk(tf <- tempfile(fileext = ".xls")))
df <- read_excel(tf)
# https://data.world/us-doi-gov/24d428dc-97cb-4ef3-9bec-5dbd4f966f12

for (i in 1:ncol(df)){
    if (is.na(df[1,i])==0){
        names(df)[i]= df[1,i]
    }
}
df=df[-1,]

nas_columns <- apply(is.na(df), 2,sum)/nrow(df)
null_columns=vector()
a=0
for (i in 1:ncol(df)){
    if (nas_columns[i]>=0.9){
        a=a+1
        null_columns[a]=i
    }
}
df=df[,-null_columns]

nas_rows <- apply(is.na(df), 1, sum)
null_rows=vector()
a=0
for (i in 1:nrow(df)){
    if (nas_rows[i]/ncol(df)>=0.8){
        a=a+1
        null_rows[a]=i
    }
    else if(is.na(df[i,1])==1){
        df[i,1]=df[i-1,1]
    }
}
df=df[-null_rows,]

#We have 1 NA and 3 "?", we are assuming these components are no present
df[is.na(df)] ="-"

b=0
for (i in 1:ncol(df)){
    for (j in 1:nrow(df)){
        if (df[j,i]=="?"){
            b=b+1
            df[j,i]="-"
        } 
    }
}

df$core=df$`Core #`
df$`Core #`=NULL

df$depth=df$"Depth (cm)"
df$"Depth (cm)"=NULL

for (i in 1:nrow(df)){
    if (df$'Grain Size'[i]=="silt v.f. sand"){
        df$'Grain Size'[i]="silt-v.f. sand"
    }
}

df= df %>% separate('Grain Size', c("grain1", "grain2"), "-")
levels(df$grain1) = c(levels(df$grain1),"f.sand", "v.f.sand", "silt", "clay")
levels(df$grain2) = c(levels(df$grain2),"f.sand", "v.f.sand", "silt", "clay")

df[sapply(df, is.character)] <- lapply(df[sapply(df, is.character)], as.factor)
levels_core=levels(df$core)

df[df=="v.f. sand"]="v.f.sand"
df[df=="v.f sand"]="v.f.sand"
revalue(df$grain1, c("f. sand"="f.sand"))


levels(df$grain2)=c(levels(df$grain2), "NA")
df$grain2[is.na(df$grain2)]<- "NA"

df_long <- gather(df, material, proportion, Quartz:Pteropods, factor_key=TRUE)
df_long[sapply(df_long, is.character)] <- lapply(df_long[sapply(df_long, is.character)], as.factor)

core_depth_selected <- df_long %>% 
  filter(depth == params$selDepth & core == params$selCore)
```


```{r echo=FALSE, warning=FALSE}
ggplot(core_depth_selected,
                             aes(x=material, y=proportion))  +  theme(legend.position = "none",
                          panel.background = element_rect(fill = "white", color = "gray60")) +
                          geom_bar(stat='identity', colour="gray60", aes(fill=material)) + 
                          scale_fill_manual(values=setNames(c("palevioletred", "lightsalmon3", "orange", "lightsteelblue4", "mediumturquoise", "khaki4", 
                                                                "gold", "mediumorchid1"),
                                                              c("Quartz", "Feldspar", "Dark Lithics", "Manganese", "Forams", 
                                                                "Sponge Spicules", "Carbonate Fragments", "Pteropods"))) +
                          xlim("Quartz", "Feldspar", "Dark Lithics", "Manganese", "Forams", 
                                                                "Sponge Sp.", "Carbonate", "Pteropods") + 
                          ylim("R", "R-P", "P", "P-C", "C", "C-A", "A")
```

<br>
The proportion levels are R, Rare (1%); P, Present (1-5%); C, Common (5-25 %); and A, Abundant (25-75%).